In [4]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
dataset = pd.read_csv('Datac.csv')
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values
print(x)

[['Kecamatan Pademangan' 'Ciu' 19]
 ['Kecamatan Pademangan' 'Anggur Orang Tua' 134]
 ['Kecamatan Pademangan' 'Guinnes' 12]
 ['Kecamatan Pademangan' 'Anggur Merah' 84]
 ['Kecamatan Pademangan' 'Rajawali' 84]
 ['Kecamatan Pademangan' 'Vodka' 4]
 ['Kecamatan Pademangan' 'Intisari' 9]
 ['Kecamatan Koja' 'Anggur Orang Tua' 13]
 ['Kecamatan Koja' 'Anggur Merah' 2]
 ['Kecamatan Koja' 'Brandy' 60]
 ['Kecamatan Koja' 'Mansion' 23]
 ['Kecamatan Koja' 'Rajawali' 55]
 ['Kecamatan Koja' 'Anggur Ginseng' 132]
 ['Kecamatan Koja' 'Vodka' 20]
 ['Kecamatan Cilincing' 'Anggur Merah' 9]
 ['Kecamatan Cilincing' 'Brandy' 181]
 ['Kecamatan Cilincing' 'Rajawali' 26]
 ['Kecamatan Cilincing' 'Kolesom Kecil' 9]
 ['Kecamatan Cilincing' 'Kolesom Besar' 10]
 ['Kecamatan Cilincing' 'Aseng' 41]
 ['KecamatanTanjung Priok' 'Brandy' 60]
 ['KecamatanTanjung Priok' 'Rajawali' 45]
 ['KecamatanTanjung Priok' 'Intisari' 3]
 ['Kecamatan Kelapa Gading' 'Guinnes' 5]
 ['Kecamatan Kelapa Gading' 'Bintang' 42]
 ['Kecamatan Kelapa 

In [5]:
print(y)

['Botol' 'Botol' 'Botol' 'Botol' 'Botol' 'Botol' 'Botol' 'Botol' 'Botol'
 'Botol' 'Botol' 'Botol' 'Botol' 'Botol' 'Botol' 'Botol' 'Botol' 'Botol'
 'Botol' 'Botol' 'Botol' 'Botol' 'Botol' 'Botol' 'Botol' 'Botol' 'Botol'
 'Botol' 'Botol' 'Botol']


In [7]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

In [8]:
print(x)

[[0.0 0.0 0.0 1.0 0.0 'Ciu' 19]
 [0.0 0.0 0.0 1.0 0.0 'Anggur Orang Tua' 134]
 [0.0 0.0 0.0 1.0 0.0 'Guinnes' 12]
 [0.0 0.0 0.0 1.0 0.0 'Anggur Merah' 84]
 [0.0 0.0 0.0 1.0 0.0 'Rajawali' 84]
 [0.0 0.0 0.0 1.0 0.0 'Vodka' 4]
 [0.0 0.0 0.0 1.0 0.0 'Intisari' 9]
 [0.0 0.0 1.0 0.0 0.0 'Anggur Orang Tua' 13]
 [0.0 0.0 1.0 0.0 0.0 'Anggur Merah' 2]
 [0.0 0.0 1.0 0.0 0.0 'Brandy' 60]
 [0.0 0.0 1.0 0.0 0.0 'Mansion' 23]
 [0.0 0.0 1.0 0.0 0.0 'Rajawali' 55]
 [0.0 0.0 1.0 0.0 0.0 'Anggur Ginseng' 132]
 [0.0 0.0 1.0 0.0 0.0 'Vodka' 20]
 [1.0 0.0 0.0 0.0 0.0 'Anggur Merah' 9]
 [1.0 0.0 0.0 0.0 0.0 'Brandy' 181]
 [1.0 0.0 0.0 0.0 0.0 'Rajawali' 26]
 [1.0 0.0 0.0 0.0 0.0 'Kolesom Kecil' 9]
 [1.0 0.0 0.0 0.0 0.0 'Kolesom Besar' 10]
 [1.0 0.0 0.0 0.0 0.0 'Aseng' 41]
 [0.0 0.0 0.0 0.0 1.0 'Brandy' 60]
 [0.0 0.0 0.0 0.0 1.0 'Rajawali' 45]
 [0.0 0.0 0.0 0.0 1.0 'Intisari' 3]
 [0.0 1.0 0.0 0.0 0.0 'Guinnes' 5]
 [0.0 1.0 0.0 0.0 0.0 'Bintang' 42]
 [0.0 1.0 0.0 0.0 0.0 'Bir' 66]
 [0.0 1.0 0.0 0.0 0.0 'Angg

In [9]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [10]:
print(y)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


In [11]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=1)

In [12]:
print(x_train)

[[0.0 1.0 0.0 0.0 0.0 'Anggur Merah' 120]
 [0.0 0.0 0.0 1.0 0.0 'Anggur Merah' 84]
 [0.0 1.0 0.0 0.0 0.0 'Bintang' 42]
 [0.0 0.0 0.0 0.0 1.0 'Intisari' 3]
 [0.0 1.0 0.0 0.0 0.0 'Guinnes' 5]
 [0.0 0.0 0.0 1.0 0.0 'Rajawali' 84]
 [0.0 0.0 0.0 1.0 0.0 'Guinnes' 12]
 [0.0 1.0 0.0 0.0 0.0 'Bir' 66]
 [0.0 0.0 0.0 1.0 0.0 'Intisari' 9]
 [1.0 0.0 0.0 0.0 0.0 'Kolesom Besar' 10]
 [0.0 0.0 1.0 0.0 0.0 'Vodka' 20]
 [0.0 0.0 1.0 0.0 0.0 'Anggur Orang Tua' 13]
 [0.0 1.0 0.0 0.0 0.0 'Brandy' 60]
 [0.0 0.0 0.0 1.0 0.0 'Anggur Orang Tua' 134]
 [1.0 0.0 0.0 0.0 0.0 'Rajawali' 26]
 [0.0 0.0 0.0 1.0 0.0 'Ciu' 19]
 [1.0 0.0 0.0 0.0 0.0 'Brandy' 181]
 [0.0 1.0 0.0 0.0 0.0 'Bir Hitam' 119]
 [0.0 1.0 0.0 0.0 0.0 'Vodka' 4]
 [0.0 0.0 1.0 0.0 0.0 'Brandy' 60]
 [0.0 0.0 1.0 0.0 0.0 'Anggur Merah' 2]
 [0.0 0.0 1.0 0.0 0.0 'Anggur Ginseng' 132]
 [0.0 0.0 1.0 0.0 0.0 'Rajawali' 55]
 [0.0 0.0 0.0 1.0 0.0 'Vodka' 4]]


In [13]:
print(x_test)

[[1.0 0.0 0.0 0.0 0.0 'Kolesom Kecil' 9]
 [0.0 0.0 0.0 0.0 1.0 'Rajawali' 45]
 [0.0 0.0 1.0 0.0 0.0 'Mansion' 23]
 [1.0 0.0 0.0 0.0 0.0 'Aseng' 41]
 [1.0 0.0 0.0 0.0 0.0 'Anggur Merah' 9]
 [0.0 0.0 0.0 0.0 1.0 'Brandy' 60]]


In [14]:
print(y_train)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


In [15]:
print(y_test)

[0 0 0 0 0 0]


In [25]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train[:, 6:] = sc.fit_transform(x_train[:, 6:])
x_test[:, 6:] = sc.transform(x_test[:, 6:])

In [26]:
print(x_train)

[[0.0 1.0 0.0 0.0 0.0 'Anggur Merah' 1.318516511453724]
 [0.0 0.0 0.0 1.0 0.0 'Anggur Merah' 0.6135670894883666]
 [0.0 1.0 0.0 0.0 0.0 'Bintang' -0.20887390280455026]
 [0.0 0.0 0.0 0.0 1.0 'Intisari' -0.9725691099336873]
 [0.0 1.0 0.0 0.0 0.0 'Guinnes' -0.9334052531578342]
 [0.0 0.0 0.0 1.0 0.0 'Rajawali' 0.6135670894883666]
 [0.0 0.0 0.0 1.0 0.0 'Guinnes' -0.796331754442348]
 [0.0 1.0 0.0 0.0 0.0 'Bir' 0.26109237850568795]
 [0.0 0.0 0.0 1.0 0.0 'Intisari' -0.8550775396061278]
 [1.0 0.0 0.0 0.0 0.0 'Kolesom Besar' -0.8354956112182012]
 [0.0 0.0 1.0 0.0 0.0 'Vodka' -0.6396763273389353]
 [0.0 0.0 1.0 0.0 0.0 'Anggur Orang Tua' -0.7767498260544214]
 [0.0 1.0 0.0 0.0 0.0 'Brandy' 0.14360080817812837]
 [0.0 0.0 0.0 1.0 0.0 'Anggur Orang Tua' 1.5926635088846963]
 [1.0 0.0 0.0 0.0 0.0 'Rajawali' -0.5221847570113757]
 [0.0 0.0 0.0 1.0 0.0 'Ciu' -0.6592582557268619]
 [1.0 0.0 0.0 0.0 0.0 'Brandy' 2.513014143117246]
 [0.0 1.0 0.0 0.0 0.0 'Bir Hitam' 1.2989345830657975]
 [0.0 1.0 0.0 0.0 0.0 'Vod

In [27]:
print(x_test)

[[1.0 0.0 0.0 0.0 0.0 'Kolesom Kecil' -0.8550775396061278]
 [0.0 0.0 0.0 0.0 1.0 'Rajawali' -0.1501281176407705]
 [0.0 0.0 1.0 0.0 0.0 'Mansion' -0.5809305421751555]
 [1.0 0.0 0.0 0.0 0.0 'Aseng' -0.22845583119247687]
 [1.0 0.0 0.0 0.0 0.0 'Anggur Merah' -0.8550775396061278]
 [0.0 0.0 0.0 0.0 1.0 'Brandy' 0.14360080817812837]]
